# General Settings
language: cpp
sudo: false

matrix:
    include:

        ### Linux/clang3.4 Builds
        ###############
        - os: linux
          compiler: clang
          addons: &clang34
            apt:
              sources: ['llvm-toolchain-precise', 'ubuntu-toolchain-r-test']
              packages: ['clang']
          env: COMPILER='clang++' BUILD_TYPE='Debug'

        - os: linux
          compiler: clang
          addons: *clang34
          env: COMPILER='clang++' BUILD_TYPE='Release'

        ### Linux/GCC Builds
        ###############
        - os: linux
          compiler: gcc
          addons: &gcc6
            apt:
              sources: ['ubuntu-toolchain-r-test']
              packages: ['g++-6']
          env: COMPILER='g++-6' BUILD_TYPE='Debug'

        - os: linux
          compiler: gcc
          addons: *gcc6
          env: COMPILER='g++-6' BUILD_TYPE='Release'

        ### OS X Builds
        ###############
        - os: osx
          osx_image: xcode8
          compiler: clang
          env: COMPILER='clang++' BUILD_TYPE='Debug'

        - os: osx
          osx_image: xcode8
          compiler: clang
          env: COMPILER='clang++' BUILD_TYPE='Release'


### Dependencies
###############################################################################
install:
    - DEPS_DIR="${TRAVIS_BUILD_DIR}/deps"
    - mkdir -p ${DEPS_DIR}
    - cd ${DEPS_DIR}
    - |
      if [ "${TRAVIS_OS_NAME}" = "linux" ]; then
        CMAKE_URL="https://cmake.org/files/v3.8/cmake-3.8.0-Linux-x86_64.tar.gz"
        mkdir cmake
        travis_retry wget --no-check-certificate --quiet -O - ${CMAKE_URL} | tar --strip-components=1 -xz -C cmake
        export PATH=${DEPS_DIR}/cmake/bin:${PATH}
      elif [ "${TRAVIS_OS_NAME}" = "osx" ]; then
        which cmake || brew install cmake
      fi


### Building
###############################################################################
before_script:
    - export CXX=${COMPILER}
    - cmake --version
    - $CXX --version
    - cd ${TRAVIS_BUILD_DIR}
    - mkdir -p build
    - cd build
    - cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -G"Unix Makefiles"

script:
    - make -j4
    - ctest -V -j 2

