# Will be replaced by git commit hash later
version: '{build}'

# fetch repository as zip archive
shallow_clone: true

os:
    - Visual Studio 2017
    - Visual Studio 2015

environment:
    matrix:
        - additional_flags: "/permissive-"

        - additional_flags: ""


matrix:
    exclude:
        -
            additional_flags: "/permissive-"
            os: Visual Studio 2015

init:
    - git config --global core.autocrlf input
    # Set build version to git commit-hash
    - ps: Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_BRANCH) - $($env:APPVEYOR_REPO_COMMIT)"

platform:
    - Win32
    - x64

configuration:
    - Debug
    - Release

before_build:
    - cmake -H. -Bbuild -A%PLATFORM%

build:
    project: build/meta.sln
    parallel: true
    verbosity: normal

test_script:
    - cd build
    - tests/tests.exe

